"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataStore = exports.Channels = void 0;
var Channels;
(function (Channels) {
    Channels["book_add"] = "book_add";
    Channels["window_toggleDevTools"] = "window_toggleDevTools";
    Channels["app_close"] = "app_close";
    Channels["dialog_message"] = "dialog_message";
    Channels["json_save"] = "json_save";
    Channels["dialog_open"] = "dialog_open";
    Channels["dialog_save"] = "dialog_save";
    Channels["window_min"] = "window_min";
    Channels["window_max"] = "window_max";
    Channels["window_resize"] = "window_resize";
    Channels["window_close"] = "window_close";
    Channels["window_new"] = "window_new";
    Channels["file_read"] = "file_read";
    Channels["file_copy"] = "file_copy";
    Channels["file_write"] = "file_write";
    Channels["db_find"] = "db_find";
    Channels["db_update"] = "db_update";
    Channels["db_delete"] = "db_delete";
    Channels["db_count"] = "db_count";
    Channels["db_create"] = "db_create";
    Channels["db_insert"] = "db_insert";
    Channels["notification"] = "notification";
    Channels["shell_open"] = "shell_open";
    Channels["dict_search"] = "dict_search";
})(Channels = exports.Channels || (exports.Channels = {}));
var DataStore;
(function (DataStore) {
    DataStore["bookshelf"] = "bookshelf";
    DataStore["bookBody"] = "bookBody";
})(DataStore = exports.DataStore || (exports.DataStore = {}));
